Input Notebook:  ./trainer_for_acd_b_new.ipynb
Output Notebook: ./papermill/trainer_for_acd_b_new.ipynb
Executing:   0%|          | 0/31 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   3%|▎         | 1/31 [00:01<00:58,  1.95s/cell]Executing:  10%|▉         | 3/31 [00:09<01:27,  3.13s/cell]Executing:  16%|█▌        | 5/31 [00:09<00:40,  1.55s/cell]Executing:  19%|█▉        | 6/31 [00:09<00:33,  1.33s/cell]Executing:  29%|██▉       | 9/31 [00:09<00:14,  1.57cell/s]Executing:  35%|███▌      | 11/31 [00:12<00:15,  1.31cell/s]Executing:  39%|███▊      | 12/31 [00:16<00:27,  1.44s/cell]Executing:  48%|████▊     | 15/31 [00:16<00:12,  1.24cell/s]Executing:  58%|█████▊    | 18/31 [00:19<00:12,  1.07cell/s]Executing:  68%|██████▊   | 21/31 [00:19<00:06,  1.63cell/s]Executing:  74%|███████▍  | 23/31 [00:29<00:13,  1.71s/cell]Executing:  77%|███████▋  | 24/31 [00:32<00:12,  1.83s/cell]Executing:  84%|████████▍ | 26/31 [00:32<00:06,  1.30s/cell]Executing:  90%|█████████ | 28/31 [00:40<00:06,  2.20s/cell]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Executing:  97%|█████████▋| 30/31 [6:48:47<1:01:49, 3709.26s/cell]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Executing: 100%|██████████| 31/31 [6:48:50<00:00, 3050.13s/cell]  Executing: 100%|██████████| 31/31 [6:48:55<00:00, 791.47s/cell] 
Input Notebook:  ./trainer_for_asc_m_new.ipynb
Output Notebook: ./papermill/trainer_for_asc_m_new.ipynb
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/site-packages/papermill/iorw.py", line 212, in read
    json.loads(path)
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/site-packages/papermill/iorw.py", line 512, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/site-packages/papermill/iorw.py", line 100, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/site-packages/papermill/iorw.py", line 216, in read
    raise e
  File "/home/ubuntu/anaconda3/envs/jeonghyeon/lib/python3.8/site-packages/papermill/iorw.py", line 206, in read
    with io.open(path, 'r', encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: './trainer_for_asc_m_new.ipynb'
